# Turbo OS - A Distro de Alta Performance
name: turbo-os  # NOME ATUALIZADO
description: Distro de Gaming e Dev baseada no Fedora Kinoite (Nvidia).
base-image: ghcr.io/ublue-os/kinoite-nvidia # Base com drivers Nvidia
image-version: latest

modules:
  # 1. FICHEIROS DE SISTEMA
  - type: files
    files:
      - source: system
        destination: /

  # 3. PACOTES DO SISTEMA (RPMs)
  - type: rpm-ostree
    install:
      - steam
      - lutris
      - gamemode
      - mangohud
      - gamescope
      - sunshine
      - htop
      - fastfetch
      - git
      - wget
      - distrobox
      - zsh
      - android-tools

  # 4. APLICAÇÕES (Flatpaks)
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (Sistema)"
      install:
        - com.discordapp.Discord
        - com.obsproject.Studio
        - com.visualstudio.code
        - com.jetbrains.IntelliJ-IDEA-Community
        - org.libretro.RetroArch
        - org.DolphinEmu.dolphin-emu
        - net.pcsx2.PCSX2
        - org.duckstation.DuckStation
        - org.ryujinx.Ryujinx

  # 5. FONTES
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack

  # 7. TRUQUE NEOFETCH
  - type: script
    scripts:
      - |
        echo 'alias neofetch="fastfetch"' >> /etc/bashrc
        echo 'alias neofetch="fastfetch"' >> /etc/zshrc
