# Turbo OS - A Distro de Alta Performance
name: turbo-os  # NOME ATUALIZADO
description: Distro de Gaming e Dev baseada no Fedora Kinoite (Nvidia).
base-image: ghcr.io/ublue-os/kinoite-nvidia # Base com drivers Nvidia
image-version: latest

modules:
  # 1. FICHEIROS DE SISTEMA
  - type: files
    files:
      - source: system
        destination: /
